### ISSUE TITLE
Vertical scrolling not working on mobile devices

### ISSUE THREAD

**Issue by kr1-ch** [gbrlsnchs/material2-carousel#9]
Cannot scroll to bottom or top in the carousel zone (only on mobile devices). This issue is probably due to these inline CSS rules:
```
    touch-action: none;
    user-select: none;
    -webkit-user-drag: none;
```

**Comment by chriswnewman** [comment]
Related to https://github.com/angular/angular/issues/10541
Implemented a fix in PR #22 
 - based on https://github.com/angular/angular/issues/10541#issuecomment-300761387 and https://github.com/angular/angular/issues/10541#issuecomment-346539242

**Comment by gbrlsnchs** [comment]
Sorry for taking long to check this issue. I will review @chriswnewman's PR as soon as possible.

**Comment by gauravaditya** [comment]
Hi, 

just wanted to know if this fix has been released ? the readme says to load the module with "forRoot()" but it doesn't seem to work.

Please let me know if i am missing something. Appreciate any help.

**Comment by gbrlsnchs** [comment]
Hi, @gauravaditya, thanks for noticing and reporting. Sorry, that was my mistake, as I approved the PR that fixed this issue but didn't release a new version on NPM, still, the README has been misleadingly modified.

I have pushed a new release and soon CI will publish the package to NPM.

**Comment by gauravaditya** [comment]
Thanks for pushing the release, was looking forward to it. :)

**Comment by gbrlsnchs** [comment]
Sorry for the inconvenience! `v0.5.1` has the fix.

**Comment by gabrieltaets** [comment]
Oddly enough, I'm using v0.5.1 but I still have this issue.
Shouldn't `<li>` have `touch-action: pan-y` instead of `none`?
I see that in the demo the element have `touch-action: pan-y`. But for some reason, in my app, it's `touch-action: none`.
